### ISSUE TITLE
Server Crashing (using LEB-ToolBox v1.6) Full Install

### ISSUE THREAD

**Issue by niceEli** [Legacy-Edition-Minigames/Minigames#49]
(log)
```
****************************
*** LEB Server Launching ***
****************************

Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[13:20:57] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.21
[13:20:57] [main/INFO]: Dependencies overridden for viafabric
[13:20:57] [main/WARN]: Warnings were found!
 - Mod 'ViaBackwards' (viabackwards) 4.5.1 recommends any version of viarewind, which is missing!
         - You should install any version of viarewind for the optimal experience.
[13:20:57] [main/INFO]: Loading 82 mods:
        - carpet 1.4.84
        - dedicatedmcupnp 1.2.1
           |-- com_fasterxml_jackson_core_jackson-annotations 2.12.4
           |-- com_fasterxml_jackson_core_jackson-core 2.12.4
           |-- com_fasterxml_jackson_core_jackson-databind 2.12.4
           \-- com_fasterxml_jackson_dataformat_jackson-dataformat-yaml 2.12.4
        - editableplayernbthack 1.1.0-1.19.2
        - fabric-api 0.70.0+1.19.2
           |-- fabric-api-base 0.4.14+6e0787e690
           |-- fabric-api-lookup-api-v1 1.6.13+93d8cb8290
           |-- fabric-biome-api-v1 9.0.21+4d0d570390
           |-- fabric-block-api-v1 1.0.2+e415d50e90
           |-- fabric-blockrenderlayer-v1 1.1.23+c6af733c90
           |-- fabric-client-tags-api-v1 1.0.4+b35fea8390
           |-- fabric-command-api-v1 1.2.14+f71b366f90
           |-- fabric-command-api-v2 2.1.10+93d8cb8290
           |-- fabric-commands-v0 0.2.31+df3654b390
           |-- fabric-containers-v0 0.1.39+df3654b390
           |-- fabric-content-registries-v0 3.5.0+7c6cd14d90
           |-- fabric-convention-tags-v1 1.2.1+27265b3490
           |-- fabric-crash-report-info-v1 0.2.8+aeb40ebe90
           |-- fabric-data-generation-api-v1 5.3.4+ad31814d90
           |-- fabric-dimensions-v1 2.1.34+0d0f210290
           |-- fabric-entity-events-v1 1.5.3+9244241690
           |-- fabric-events-interaction-v0 0.4.32+4d0d570390
           |-- fabric-events-lifecycle-v0 0.2.32+df3654b390
           |-- fabric-game-rule-api-v1 1.0.24+b6b6abb490
           |-- fabric-item-api-v1 1.6.2+fa140d5990
           |-- fabric-item-groups-v0 0.3.37+9244241690
           |-- fabric-key-binding-api-v1 1.0.24+aaaf9d3390
           |-- fabric-keybindings-v0 0.2.22+df3654b390
           |-- fabric-lifecycle-events-v1 2.2.3+1b46dc7890
           |-- fabric-loot-api-v2 1.1.11+83a8659290
           |-- fabric-loot-tables-v1 1.1.14+9e7660c690
           |-- fabric-message-api-v1 5.0.6+93d8cb8290
           |-- fabric-mining-level-api-v1 2.1.22+33fbc73890
           |-- fabric-models-v0 0.3.20+c6af733c90
           |-- fabric-networking-api-v1 1.2.9+6e0787e690
           |-- fabric-networking-v0 0.3.26+df3654b390
           |-- fabric-object-builder-api-v1 4.1.4+4d0d570390
           |-- fabric-particles-v1 1.0.13+4d0d570390
           |-- fabric-registry-sync-v0 0.9.30+9244241690
           |-- fabric-renderer-api-v1 1.1.1+6e0787e690
           |-- fabric-renderer-indigo 0.6.18+aeb40ebe90
           |-- fabric-renderer-registries-v1 3.2.23+df3654b390
           |-- fabric-rendering-data-attachment-v1 0.3.18+6e0787e690
           |-- fabric-rendering-fluids-v1 3.0.10+4d0d570390
           |-- fabric-rendering-v0 1.1.26+df3654b390
           |-- fabric-rendering-v1 1.12.0+08b73de490
           |-- fabric-resource-conditions-api-v1 2.1.2+aae9039d90
           |-- fabric-resource-loader-v0 0.8.3+251d254a90
           |-- fabric-screen-api-v1 1.0.31+4d0d570390
           |-- fabric-screen-handler-api-v1 1.3.5+1cc24b1b90
           |-- fabric-sound-api-v1 1.0.2+c4f28df590
           |-- fabric-textures-v0 1.0.23+aeb40ebe90
           |-- fabric-transfer-api-v1 2.1.4+4d0d570390
           \-- fabric-transitive-access-wideners-v1 1.3.3+08b73de490
        - fabricloader 0.14.21
        - ferritecore 5.0.3
        - java 19
        - krypton 0.2.1
           \-- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT
        - lithium 0.10.4
        - minecraft 1.19.2
        - minimotd-fabric 2.0.9
           \-- adventure-platform-fabric 5.4.0-SNAPSHOT
                |-- net_kyori_adventure-api 4.11.0
                |-- net_kyori_adventure-key 4.11.0
                |-- net_kyori_adventure-platform-api 4.1.1
                |-- net_kyori_adventure-text-logger-slf4j 4.11.0
                |-- net_kyori_adventure-text-minimessage 4.11.0
                |-- net_kyori_adventure-text-serializer-gson 4.11.0
                |-- net_kyori_adventure-text-serializer-plain 4.11.0
                |-- net_kyori_examination-api 1.3.0
                \-- net_kyori_examination-string 1.3.0
        - nochatreports 1.19.2-v1.13.12
           |-- fabric-rendering-v1 1.11.0+73145abb90
           \-- fabric-screen-api-v1 1.0.27+93d8cb8290
        - servercore 1.3.3-1.19.2
           |-- com_electronwill_night-config_core 3.6.6
           |-- com_electronwill_night-config_toml 3.6.6
           |-- com_github_llamalad7_mixinextras 0.1.0
           |-- fabric-permissions-api-v0 0.2-SNAPSHOT
           |-- me_lucko_spark-api 0.1-SNAPSHOT
           \-- placeholder-api 2.0.0-pre.1+1.19.2
        - serverutils 1.0.5-1.19
           \-- fantasy 0.4.7-kyrpt-1.19.2
        - snowballkb 1.2-1.19
        - starlight 1.1.1+fabric.ae22326
        - styledplayerlist 2.2.2+1.19.1
           \-- player-data-api 0.2.1+1.19
        - viabackwards 4.5.1
        - viafabric 0.4.9+22-main
           |-- cotton-client-commands 1.1.0+1.15.2
           |-- org_yaml_snakeyaml 1.33
           |-- viafabric-mc119 0.4.9+22-main
           \-- viaversion 4.5.0
        - vmp 0.2.0+beta.7.23
[13:20:57] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/EliAv/Downloads/MC%20Legacy/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[13:20:57] [main/INFO]: Compatibility level set to JAVA_17
[13:20:58] [main/INFO]: Loaded configuration file for Lithium: 106 options available, 3 override(s) found
[13:20:58] [main/INFO]: [ServerCore] Loading...
[13:20:58] [main/INFO]: Successfully started async appender with [ServerGuiConsole, SysOut, File]
[13:20:58] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[13:20:58] [main/WARN]: Force-disabling mixin 'alloc.chunk_ticking.ServerChunkManagerMixin' as rule 'mixin.alloc.chunk_ticking' (added by mods [servercore]) disables it and children
[13:20:58] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton, vmp]) disables it and children
[13:20:58] [main/WARN]: Error loading class: me/lucko/luckperms/fabric/listeners/FabricConnectionListener (java.lang.ClassNotFoundException: me/lucko/luckperms/fabric/listeners/FabricConnectionListener)
[13:20:58] [main/WARN]: Error loading class: com/ishland/c2me/notickvd/common/NoTickChunkSendingInterceptor (java.lang.ClassNotFoundException: com/ishland/c2me/notickvd/common/NoTickChunkSendingInterceptor)
[13:21:00] [main/INFO]: Mixing server.MixinPlayer from nochatreports.mixins.json into net.minecraft.class_1657
[13:21:04] [main/INFO]: Building unoptimized datafixer
[13:21:06] [main/INFO]: Mixing server.MixinServerGamePacketListenerImpl from nochatreports.mixins.json into net.minecraft.class_3244
[13:21:06] [main/INFO]: Compression will use Java, encryption will use Java
[13:21:07] [main/INFO]: Done initializing MiniMOTD
[13:21:07] [main/INFO]: KONNICHIWA ZA WARUDO!
[13:21:07] [main/INFO]: Default JVM text encoding is: UTF-8
[13:21:07] [main/INFO]: Reading config file NoChatReports/NCR-Common.json...
[13:21:07] [main/INFO]: Writing config file NoChatReports/NCR-Common.json...
[13:21:07] [main/WARN]: Failed to load config, using default values: config\snowballkb.json (The system cannot find the file specified)
[13:21:07] [Via-Mappingloader-0/INFO]: Loading 1.12 -> 1.13 mappings...
[13:21:07] [Via-Mappingloader-1/INFO]: Loading 1.13 -> 1.13.2 mappings...
[13:21:07] [Via-Mappingloader-2/INFO]: Loading 1.13.2 -> 1.14 mappings...
[13:21:08] [Via-Mappingloader-3/INFO]: Loading 1.14 -> 1.15 mappings...
[13:21:08] [Via-Mappingloader-0/INFO]: Loading block connection mappings ...
[13:21:08] [Via-Mappingloader-4/INFO]: Loading 1.15 -> 1.16 mappings...
[13:21:08] [Via-Mappingloader-4/INFO]: Loading 1.16 -> 1.16.2 mappings...
[13:21:08] [Via-Mappingloader-4/INFO]: Loading 1.16.2 -> 1.17 mappings...
[13:21:08] [Via-Mappingloader-0/INFO]: Loading 1.17 -> 1.18 mappings...
[13:21:08] [Via-Mappingloader-0/INFO]: Loading 1.18 -> 1.19 mappings...
[13:21:08] [Via-Mappingloader-0/INFO]: Loading 1.19 -> 1.19.3 mappings...
[13:21:08] [main/INFO]: Loading translations...
[13:21:08] [Via-Mappingloader-0/INFO]: Loading 1.10 -> 1.9.4 mappings...
[13:21:08] [Via-Mappingloader-0/INFO]: Loading 1.11 -> 1.10 mappings...
[13:21:08] [Via-Mappingloader-0/INFO]: Loading 1.12 -> 1.11 mappings...
[13:21:08] [Via-Mappingloader-0/INFO]: Loading 1.13 -> 1.12 mappings...
[13:21:08] [Via-Mappingloader-4/INFO]: Loading 1.13.2 -> 1.13 mappings...
[13:21:08] [Via-Mappingloader-4/INFO]: Loading 1.14 -> 1.13.2 mappings...
[13:21:08] [Via-Mappingloader-0/INFO]: Loading 1.15 -> 1.14 mappings...
[13:21:08] [Via-Mappingloader-0/INFO]: Loading 1.16 -> 1.15 mappings...
[13:21:08] [Via-Mappingloader-4/INFO]: Loading 1.16.2 -> 1.16 mappings...
[13:21:08] [Via-Mappingloader-0/INFO]: Loading 1.17 -> 1.16.2 mappings...
[13:21:08] [Via-Mappingloader-0/INFO]: Loading 1.18 -> 1.17 mappings...
[13:21:08] [Via-Mappingloader-0/INFO]: Loading 1.19 -> 1.18 mappings...
[13:21:08] [Via-Mappingloader-0/INFO]: Loading 1.19.3 -> 1.19 mappings...
[13:21:08] [ViaFabric-0/WARN]: There is a newer plugin version available: 4.6.2, you're on: 4.5.0
[13:21:08] [ViaFabric-0/INFO]: ViaVersion detected server version: 1.19.1/2 (760)
[13:21:08] [ViaFabric-0/INFO]: Finished mapping loading, shutting down loader executor!
[13:21:08] [main/INFO]: [STDOUT]: Raknetify: Warning: net.minecraft.class_2635 not found for raknet multi-channel
[13:21:08] [main/INFO]: Mixing server.MixinServerboundChatPacket from nochatreports.mixins.json into net.minecraft.class_2797
[13:21:08] [main/INFO]: [STDOUT]: Raknetify: Warning: net.minecraft.class_2755 not found for raknet multi-channel
[13:21:08] [main/INFO]: [STDOUT]: Raknetify: Warning: net.minecraft.class_2762 not found for raknet multi-channel
[13:21:08] [main/INFO]: [STDOUT]: Raknetify: Warning: net.minecraft.class_2610 not found for raknet multi-channel
[13:21:08] [main/INFO]: [STDOUT]: Raknetify: Warning: net.minecraft.class_2612 not found for raknet multi-channel
[13:21:08] [main/INFO]: [STDOUT]: Raknetify: Warning: net.minecraft.class_2698 not found for raknet multi-channel
[13:21:08] [main/INFO]: [STDOUT]: Raknetify: Warning: net.minecraft.class_2809 not found for raknet multi-channel
[13:21:08] [main/INFO]: [STDOUT]: Raknetify: Warning: net.minecraft.class_2644 not found for raknet multi-channel
[13:21:08] [main/INFO]: [STDOUT]: Raknetify: Warning: net.minecraft.class_2730 not found for raknet multi-channel
[13:21:08] [main/INFO]: [STDOUT]: Raknetify: Warning: net.minecraft.class_5747 not found for raknet multi-channel
[13:21:09] [main/INFO]: Krypton is now accelerating your Minecraft server's networking stack ≡ƒÜÇ
[13:21:09] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:21:09] [main/WARN]: Missing data pack fabric
[13:21:09] [main/INFO]: Found new data pack Fabric Mods, loading it automatically
[13:33:02] [main/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: com.google.gson.JsonParseException: Error loading registry data: No key precipitation in MapLike[{"temperature":-0.5,"downfall":0.4,"effects":{"sky_color":8625919,"fog_color":12638463,"water_color":8630498,"water_fog_color":329011},"spawners":{},"spawn_costs":{},"carvers":{},"features":[],"has_precipitation":true}]
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
        at net.minecraft.server.Main.main(Main.java:194) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.21.jar:?]
Caused by: com.google.gson.JsonParseException: Error loading registry data: No key precipitation in MapLike[{"temperature":-0.5,"downfall":0.4,"effects":{"sky_color":8625919,"fog_color":12638463,"water_color":8630498,"water_fog_color":329011},"spawners":{},"spawn_costs":{},"carvers":{},"features":[],"has_precipitation":true}]
        at net.minecraft.class_5455.method_34849(class_5455.java:298) ~[server-intermediary.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraft.class_5455.method_30526(class_5455.java:298) ~[server-intermediary.jar:?]
        at net.minecraft.class_5455.method_30519(class_5455.java:292) ~[server-intermediary.jar:?]
        at net.minecraft.class_6903.method_40413(class_6903.java:32) ~[server-intermediary.jar:?]
        at net.minecraft.class_6903.method_40412(class_6903.java:25) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.method_43613(Main.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_7237.method_42098(class_7237.java:24) ~[server-intermediary.jar:?]
        at net.minecraft.class_6904.method_40431(class_6904.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.method_43612(Main.java:158) ~[server-intermediary.jar:?]
        at net.minecraft.class_156.method_43498(class_156.java:952) ~[server-intermediary.jar:?]
        at net.minecraft.class_156.method_43499(class_156.java:946) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:156) ~[server-intermediary.jar:?]
        ... 4 more
Press any key to continue . . .

***************************
*** LEB Server Stopping ***
***************************

Press ENTER to return to the main menu . . .
```
(end of log)

**Comment by DBTDerpbox** [comment]
I'm not sure if you noticed, but ToolBox is marked as not supported currently, plans for a complete rewrite of it are planned, but the current version is completely broken at the moment

![image](https://github.com/Legacy-Edition-Minigames/Minigames/assets/65347035/c4b53096-611f-4805-ab4a-e6c08c3afd17)
